title: The Minodu Project
description: >-
  Documentation and presentation for the Minodu Project.
baseurl: ""
url: "https://minodulcn.github.io"
github_username: minodulcn
author: Minodu Team

theme: minima
minima:
  skin: classic

header_pages:
  - index.md
  - about/index.md
  - setup/index.md
  - docs/index.md

header_image: /assets/images/minodu-logo.jpg

plugins:
  - jekyll-feed
  - jekyll-seo-tag
